## Иерархия исключений

В Python присутствует строгая иерархия исключений, вершиной которой является тип `BaseException`.

Тип `BaseException` является классом самого верхнего уровня и базовым для всех прочих классов исключений.

**Дерево встроенных исключений** выглядит так:

```no-highlight
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
           +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```

По дереву видно, что исключения `IndexError` и `KeyError` являются **потомками (наследниками)** исключения `LookupError`, которое является потомком `Exception`. В то время как исключения `FloatingPointError, OverflowError` и `ZeroDivisionError` являются потомками исключения `ArithmeticError`.  
  
![](https://ucarecdn.com/0f44ce67-d174-42d1-bd69-840776b1d177/)Тип `Exception` – базовый класс для большинства встроенных в Python исключений. Именно его, а не `BaseException`, необходимо наследовать при создании пользовательского класса исключения.

Для проверки родства классов исключений можно использовать встроенную функцию `issubclass()`, которая указывает на то, является ли некоторый класс потомком указанного класса или нет.

Приведенный ниже код:

```python
print(issubclass(IndexError, LookupError))
print(issubclass(KeyError, Exception))
print(issubclass(ZeroDivisionError, ArithmeticError))

print(issubclass(IndexError, ArithmeticError))
print(issubclass(FloatingPointError, OverflowError))
```

выводит:

```no-highlight
True
True
True
False
False
```

Важно помнить, что если у нас используется несколько блоков `except`, то первыми нужно указывать наиболее конкретные. Иначе мы можем оказаться в ситуации вроде этой:

```python
try:
    nums = [10, 5, 20, 25]
    print(nums[100])
except Exception:
    print('Произошла ошибка!')
except (KeyError, IndexError):
    print('Ошибка связанная с индексом!')
```

Здесь первый блок `except` отлавливает вообще все исключения, ведь любое конкретное исключение наследуется от типа `Exception`. Второй блок `except` не имеет шанса хоть раз быть выполненным.

![](https://ucarecdn.com/6640fec0-3fad-448c-be73-09dce1c19fb8/)   Обработчик исключений может поймать не только указанные типы исключений, но и всех их потомков.

## Работа с объектом возбужденного исключения

Если нужен доступ к сгенерированному исключению как к объекту, то используется специальный синтаксис.

Приведенный ниже код:

```python
try:
    nums = [10, 5, 20, 25]
    print(nums[100])
except (KeyError, IndexError) as err:    # записываем сгенерированное исключение в переменную err
    print(err)
    print(type(err))
```

выводит:

```1c
list index out of range
<class 'IndexError'>
```

В данном примере в переменную `err` попадает объект типа `IndexError`.

Посмотреть все атрибуты объекта сгенерированного исключения можно с помощью встроенной функции `dir()`.

Приведенный ниже код:

```python
try:
    print(1 / 0)
except ZeroDivisionError as err:
    print(dir(err))
```

выводит:

```no-highlight
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'with_traceback']
```

Наибольший интерес представляет из себя атрибут `args`, о котором будет рассказано ниже.

![](https://ucarecdn.com/496403d8-7fa9-4ca1-a4bd-0a1494510993/)В имени `err` нет ничего особенного. Это просто имя, которое мы выбрали для примеров. Можно использовать любое имя по своему выбору. Обычно используют имена `err, exp, e`.

Если при обработке всех исключений одним блоком `except` мы хотим получить доступ к объекту исключения, то нужно явно указать его тип.

Приведенный ниже код:

```python
try:
    х = 1 / 0
except as err:
    print(err)
```

синтаксически неверен.

Для исправления кода мы пишем:

```python
try:
    х = 1 / 0
except Exception as err:
    print(err)
```

## Примечания

**Примечание 1.** Для получения информации об исключении можно воспользоваться функцией `exc_infо()` из модуля `sys`. Данная функция возвращает кортеж из трех значений: типа исключения, значения и объекта с трассировочной информацией об исключении, которое в данный момент обрабатывается.

Приведенный ниже код:

```python
from sys import exc_info

try:
    х = 1 / 0
except Exception as err:
    print(exc_info())
```

выводит:

```no-highlight
(<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000001BEEF80E840>)
```

Преобразовать эти значения в удобочитаемый вид позволяет модуль `traceback`.

**Примечание 2.** Таблица основных типов исключений.

|Тип исключения|Описание|
|---|---|
|`BaseException`|является классом самого верхнего уровня и базовым для всех прочих  <br>классов исключений|
|`Exception`|базовый класс для большинства встроенных в Python исключений. Именно  <br>его, а не `BaseException`, необходимо наследовать при создании пользовательского класса  <br>исключения|
|`AssertionError`|возбуждается инструкцией `assert`|
|`AttributeError`|возбуждается при попытке обращения к несуществующему атрибуту объекта|
|`EOFError`|возбуждается функцией `input()` при достижении конца файла с вводными данными|
|`ImportError`|возбуждается, если невозможно импортировать модуль или пакет|
|`IndexError`|возбуждается при попытке получить элемент коллекции по несуществующему индексу|
|`KeyError`|возбуждается при попытке получить элемент коллекции по несуществующему ключу|
|`MemoryError`|возбуждается, если интерпретатору существенно не хватает оперативной памяти|
|`NameError`|возбуждается при попытке обратиться к необъявленной переменной|
|`TypeError`|возбуждается при несоответствии типов|
|`ValueError`|возбуждается при передаче в функцию аргумента с неподдерживаемым значением|
|`ZeroDivisionError`|возбуждается при попытке выполнить деление на ноль|
|`NotImplementedError`|возбуждается, если наследник класса не переопределил метод, который должен был переопределить|

**Примечание 3.** Класс, от которого производится наследование, называется базовым, родительским или суперклассом. Новый класс называется потомком, наследником, дочерним или производным классом. Базовым классом для большинства встроенных в Python исключений является `Exception`.