## Оператор assert

Оператор `assert` позволяет нам писать проверки работоспособности нашего кода. Эти проверки обычно называют **утверждениями**. Мы используем такие утверждения для того чтобы убедиться, остаются ли верными определенные условия во время разработки программы.

Если какое-либо из утверждений оказывается ложным, то это означает, что в программе есть ошибка. Если все утверждения истинны, то в программе ошибок нет.

Таким образом, утверждения — это удобный инструмент для документирования, отладки и тестирования кода во время разработки. После того как мы отладили и протестировали наш код с помощью утверждений, мы можем их отключить.

![](https://ucarecdn.com/215356d7-173d-4e9b-af30-d8bc3f67a4ae/)   Утверждения могут сделать код более эффективным, устойчивым и надежным.

Оператор `assert` – это встроенный оператор используемый для проверки того, является ли заданное утверждение истинным или ложным. Если утверждение истинно, то ничего не происходит и выполняется следующая строка кода. Если же утверждение ложно, оператор `assert` останавливает выполнение программы и подобно оператору `raise` возбуждает исключение `AssertionError`.

Синтаксис использования оператора `assert` следующий:

```python
assert <утверждение>
```

Также можно добавить дополнительное сообщение, которое описывает подробности возникновения исключительной ситуации. В таком случае синтаксис оператора `assert` будет следующий:

```python
assert <утверждение>, <сообщение>
```

### Примеры использования оператора assert

**Пример 1.** Приведенный ниже код:

```python
age = 29                # возраст человека

assert age > 0, 'Возраст должен быть положительным числом'
```

использует оператор `assert` для проверки того, является ли возраст положительным числом. В данном случае утверждение `age > 0` истинно, поэтому оператор `assert` ничего не делает. Если бы переменная `age` имела отрицательное значение, то оператором `assert` было бы возбуждено исключение `AssertionError`.

**Пример 2.** При выполнении операции деления следует учитывать, что на ноль делить нельзя. Если делитель окажется равным нулю, будет возбуждено исключение `ZeroDivisionError`.

Приведенный ниже код:

```python
num1 = 20
num2 = 0

assert num2 != 0, 'Делитель равен нулю.'

print('Частное равно:', num1 / num2)
```

использует оператор `assert` для проверки того, не равен ли нулю делитель. В данном случае утверждение `num2 != 0` ложно, поэтому оператором `assert` будет возбуждено исключение `AssertionError` вместе с добавленным нами сообщением.

Если изменить значение переменной `num2` на `10` и выполнить нашу программу снова, то на этот раз утверждение `num2 != 0` окажется истинным и исключение возбуждено не будет. Таким образом, на экран выведется результат деления:

```no-highlight
Частное равно: 2.0
```

## Примечания

 **Примечание 1.** Запись 

```python
assert <утверждение>, <сообщение>
```

примерно эквивалентна записи: 

```python
if not <утверждение>:
    raise AssertionError(<сообщение>)
```

**Примечание 2.** Обратите внимание на то, что `assert` – это именно оператор, а не функция. При использовании `assert` мы не указываем круглые скобки.

Код с ошибкой:

```
assert(2 + 2 == 5, "Houston we've got a problem")
```

Правильный код:

```
assert 2 + 2 == 5, "Houston we've got a problem"
```

Причина по которой код со скобками содержит ошибку заключается в том, что оператору `assert` подается на вход кортеж:

```
(2 + 2 == 5, "Houston we've got a problem")
```

который эквивалентен кортежу:

```
(False, "Houston we've got a problem")
```

и имеет значение `True` с точки зрения языка Python, поскольку любой непустой кортеж в Python приводится к значению `True`.

**Примечание 3.** Оператор `assert` — это средство отладки, а не механизм обработки ошибок времени выполнения программы (исключений). Цель использования оператора `assert` состоит в том, чтобы позволить разра­ботчикам как можно скорее найти вероятную первопричину ошибки. Если в программе ошибки нет, то исключение `AssertionError` никогда не должно возникнуть. В связи с этим не следует писать код, который явно обрабатывает исключения `AssertionError` с помощью конструкции `try-except`.

**Примечание 4.** Инструкция `assert` предназначена для того чтобы сооб­щать разработчикам о неустранённых ошибках в программе. Инструкция `assert` не предназначена для того чтобы сигнализировать об ожидаемых ошибочных условиях, таких как ошибка «Файл не найден», где пользователь может предпринять корректирующие действия или просто попро­бовать еще раз.

**Примечание 5.** Сформулируем основные тезисы относительно оператора `assert`:

- оператор `assert` — это средство отладки, которое проверяет утверждение, выступающее в качестве внутренней самопроверки вашей программы
- оператор `assert` должен применяться только для того чтобы по­могать разработчикам идентифицировать ошибки. Он не является механизмом обработки ошибок времени выполнения программы (исключений)
- оператор `assert` может быть глобально отключен в настройках интерпретатора