Python является языком с управляемой памятью, то есть программисту, пишущему код на Python, не нужно беспокоиться о работе с памятью и заниматься ее освобождением. Как только данные программы (объекты) становятся не нужны, сборщик мусора автоматически удаляет их и освобождает память, которую они занимали.

  Почитать про устройство и механизмы очистки памяти в Python можно по [[Механизмы очистки памяти]]

Однако при работе с **внешними ресурсами**, такими как файлы, очень важно своевременно их освобождать (закрывать). В некоторых случаях Python может самостоятельно закрыть файл, но лучше на это не рассчитывать и закрывать файл явно.

Приведенный ниже код:

```python
file = open('output.txt', mode='w', encoding='utf-8')
file.write('Python generation!')
file.close()
```

создает текстовый файл с именем `output.txt` и записывает в него строку текста `Python generation!`.

Ручное закрытие файлов, а также отдача закрытия на откуп Python, обладают одним существенным недостатком: если между открытием файла и его закрытием будет возбуждено исключение, то файл может остаться открытым и недоступным для других процессов, что может привести к проблемам. В лучшем случае файл окажется открыт слишком долго, а в худшем случае не сохранится часть данных.

Вывод данных в файл при помощи методов `write()` и `writelines()` буферизируется поэтому записываемые данные могут попасть на диск не сразу. Для форсирования сброса можно использовать файловый метод `flush()`.

Для того чтобы гарантировать закрытие файла даже при наличии исключений, мы можем использовать конструкцию `try-finally`.

Приведенный ниже код:

```python
file = open('output.txt', mode='w', encoding='utf-8')

try:
    file.write('Python generation!')
finally:
    file.close()
```

гарантированно закрывает файл, даже если между его открытием и закрытием будет возбуждено исключение. Мы также можем обработать возникшее исключение с помощью блока `except`, после чего закрыть файл:

```python
file = open('output.txt', mode='w', encoding='utf-8')

try:
    file.write('Python generation!')
except Exception as error:
    print(f'При записи в файл возникла ошибка: {error}')
finally:
    file.close()
```