Таймаут timeout

Когда мы отправляем запрос к сайту, наш парсер должен ожидать ответа от сервера, прежде чем продолжить выполнение. Если ваши запросы проходят через прокси-сервер, время ожидания может значительно увеличиться. По умолчанию, библиотека `requests` будет ждать ответа неопределённое время. Именно поэтому вы почти всегда должны задавать явный тайм-аут для каждого запроса.

`timeout` определяет максимальное время (в секундах), которое метод `.get()` будет ждать ответа от сервера. 

`timeout` может быть числом (например, `timeout=1.5` ожидает 1.5 секунды) или кортежем для разделения времени на два этапа: подключение (`connect timeout`) и чтение (`read timeout`). Например, `timeout=(3.05, 27)` установит тайм-аут подключения в 3.05 секунды и тайм-аут чтения в 27 секунд.

Если установить `timeout=**None**`, `.get()` будет ждать ответа неопределённо долго. Это может быть рискованно, если сервер никогда не ответит или ответит с большой задержкой.

### Практические Сценарии

- Задание короткого тайм-аута может быть полезным для "быстрых" запросов, где задержка в ответе считается недопустимой.
- Для "медленных" запросов, например, когда ожидается большой объем данных, можно установить большое значение тайм-аута.

### Обработка Исключений

- Рекомендуется обрабатывать исключения, связанные с тайм-аутом, для корректного завершения программы или попытки повторного запроса.

```
import requests

try:
    response = requests.get("http://example.com", timeout=.1)
except Exception as e:
    # Узнаем имя возникшего исключения
    print(e.__class__.__name__)
```

Вывод:

```
​​​​​​​ConnectTimeout
```

`ConnectTimeout` — это тип исключения, с которым вы можете столкнуться во время программирования, особенно при работе с сетевыми запросами. Это исключение обычно возникает, когда ваша программа пытается установить соединение с сервером (например, через HTTP-запрос), и сервер не отвечает в течение предопределенного временного интервала (таймаута).

- **Тайм-аут соединения**: `ConnectTimeout` указывает на то, что попытка подключения к серверу превысила установленный временной предел. Это не обязательно означает, что сервер не работает, а скорее, что не удалось установить соединение в заданное время.
    
- **Причины**: Может быть несколько причин, по которым возникает `ConnectTimeout`, включая проблемы с сетью, перегруженный или недоступный сервер, или неправильно настроенные параметры таймаута в вашем запросе.
    
- **Обработка исключения**: Правильная обработка `ConnectTimeout` включает в себя попытку повторного подключения, возможно, с увеличенным временем ожидания, или отображение сообщения об ошибке пользователю. Также стоит рассмотреть возможность логирования таких ошибок для последующего анализа.
    

```
import requests
from requests.exceptions import ConnectTimeout

try:
    response = requests.get("http://example.com", timeout=5)  # timeout в секундах
except ConnectTimeout:
    print("Connection to the server timed out.")
    # Здесь могут быть дополнительные действия, например, повторный запрос или логирование ошибки.
```

Давайте напишем код, чтобы убедиться, что время ожидания запроса через несуществующий прокси-сервер будет действительно значительным.

```
import requests
import time

url = 'http://httpbin.org/get'

proxies = {
    'http': 'http://200.12.55.90:80',
    'https': 'http://200.12.55.90:80'
}
start = time.perf_counter()
try:
    requests.get(url=url, proxies=proxies)
except requests.exceptions.ProxyError as e:
    print(f'wait time = {time.perf_counter() - start}')
    print(e)
```

Вывод:

```
wait time = 21.05327620008029
HTTPConnectionPool(host='200.12.55.90', port=80): 
Max retries exceeded with url: http://httpbin.org/get (Caused by ProxyError('Unable to connect to proxy',
ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000269A7DE8290>, 
'Connection to 200.12.55.90 timed out. (connect timeout=None)')))
```

У меня время ожидания ответа на запрос составило 21 секунду. Чтобы сократить это время до 1 секунды, напишем тот же код, но добавим атрибут `timeout=1`. 

```
import requests
import time

url = 'http://httpbin.org/get'

proxies = {
    'http': 'http://200.12.55.90:80',
    'https': 'http://200.12.55.90:80'
}
start = time.perf_counter()
try:
    requests.get(url=url, proxies=proxies, timeout=1)
except requests.exceptions.ProxyError as e:
    print(f'wait time = {time.perf_counter() - start}')
    print(e)
```

Вывод:

```
wait time = 1.0123972999863327
HTTPConnectionPool(host='200.12.55.90', port=80): 
Max retries exceeded with url: http://httpbin.org/get (Caused by ProxyError('Unable to connect to proxy', 
ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021924D68290>, 
'Connection to 200.12.55.90 timed out. (connect timeout=1)')))
```

- **`wait time = 1.0123972999863327`**: время затраченное на выполнение всех операций едва превысило 1 секунду.
- `**HTTPConnectionPool(host='200.12.55.90', port=80)**`: попытка установления соединения была сделана с прокси-сервером на IP-адресе `200.12.55.90` через порт `80`.
    
- `**Max retries exceeded with url: [http://httpbin.org/get](http://httpbin.org/get)**`: было сделано максимальное количество попыток подключения к указанному URL (в данном случае `http://httpbin.org/get`), но все они не увенчались успехом.
    
- `**Caused by ProxyError('Unable to connect to proxy'**`: основная причина ошибки — невозможность установления соединения с прокси-сервером.
    
- **`ConnectTimeoutError`**: Это класс исключения, который указывает на то, что попытка соединения превысила установленное время ожидания. Это означает, что при попытке установить соединение с сервером (или, в данном случае, с прокси-сервером) в указанный период времени соединение не было установлено.
    
- **`Connection to 200.12.55.90 timed out`**: Попытка соединения с IP-адресом `200.12.55.90` (прокси-сервер) превысила установленный временной предел ожидания и, следовательно, завершилась неудачно.
    
- **`connect timeout=1`**: Здесь `1` указывает на значение тайм-аута соединения в секундах. Это означает, что система ожидала установления соединения в течение 1 секунды, прежде чем прервать попытку соединения из-за истечения времени.
    

** **Почему при работе с proxy обрабатывается `requests.exceptions.ProxyError`**

В библиотеке `requests`, когда вы используете прокси, все исключения, связанные с соединением через прокси-сервер, включая таймауты подключения, оборачиваются в `ProxyError`. Это делается для того, чтобы можно было более чётко понять контекст ошибки. Таймаут подключения (`ConnectTimeout`) — это частный случай ошибки соединения, и если он происходит в контексте работы с прокси, то `requests` считает это частью ошибки прокси.  
  
Как это работает:

- Когда вы делаете запрос через прокси, библиотека `requests` использует `urllib3` для управления низкоуровневыми операциями с сетью.
- Если возникает таймаут при попытке установить соединение через прокси, `urllib3` выбрасывает исключение `ConnectTimeoutError`.
- Библиотека `requests` перехватывает это исключение и оборачивает его в `ProxyError`, добавляя дополнительную информацию о том, что ошибка связана с прокси-сервером.
- В результате, если вы попытаетесь перехватить исключение `Timeout`, ваш обработчик не сработает для таймаутов, возникших в контексте прокси, поскольку они теперь представлены как `ProxyError`.

Это похоже на паттерн "обёртывание исключений" (exception wrapping), который используется во многих библиотеках для обеспечения более детального контроля над обработкой ошибок, связанных с определёнными условиями выполнения программы.

#ПарсингPython 